const resourceDir = document.currentScript.getAttribute('src').replace(/[^/]*$/, '');
const resource = p => resourceDir + p;
const table = (key, columns, rows) => deck.table(key, rows, { columns });
const compare = (key, a, b, c, d) => deck.compare(key, [{title:a,body:b},{title:c,body:d}]);
const page = (id, section, title, lead, art, point, source, instruction) => ({id, section, title, lead, art, point, detail:`來源：本書 ${source}。技術內容為教學整理；公司資訊截至 2026-08-31。`, instruction});
function capacity(demand, seconds, oee) {
  const monthly = 3600 / seconds * 720 * oee / 100;
  const needed = Math.ceil(demand / monthly);
  return { monthly, needed, added: Math.max(0, needed - 6) };
}
const capacityPreview = '<div class="gpm-result" data-key="capacity-preview"><div><small>單機有效月產能</small><strong>15,120 <em>件</em></strong></div><div><small>需求 80,000 件／月</small><strong>6 <em>台</em></strong></div><div><small>已有 6 台，新增</small><strong>0 <em>台</em></strong></div></div>';
const story = {
 title:'從先進封裝看懂均豪｜全書導讀', label:'GPM 全書導讀', transition:'fade',
 attachments:[{label:'來源與閱讀說明',href:resource('sources.html'),note:'離線來源索引'}],
 pages:[
 deck.cover({title:'從先進封裝<br>看懂均豪',meta:'製程、設備、良率與客戶需求<br>全書導讀 · 非半導體背景讀者<br>公司資料快照：2026-08-31',instruction:'先問大家：看到先進封裝擴產，會不會直接想到設備商訂單？這份導讀會補上中間缺少的製程與證據。提醒公司資訊沿用書籍快照。'}),
 page('reasoning','01 / 建立封裝地圖','一則消息，需要走完六段推理','本書的目標：看得出需求如何成立，也看得出證據在哪裡中斷。',deck.steps('chain',['產品需求','封裝結構','製程步驟','缺陷與量測','設備需求','供應證據']),'每一段都要能回答「為什麼」，最後一段還要回答「誰證實」。','導讀、16','由左向右講一遍。指出前五段能推導設備類別，最後一段才能連到個別公司。'),
 page('ai','01 / 建立封裝地圖','AI 晶片需要更快地取得資料','運算單元再多，也要等記憶體把資料送過來。',compare('ai','把晶片做得更小','可改善運算密度，但還要面對記憶體頻寬、資料搬運功耗與大晶粒良率。','把不同晶片接得更近','Chiplet 與 HBM 透過封裝互連合作，增加連線密度、縮短資料路徑。'),'先進封裝把系統問題帶進製造現場，也增加互連、散熱與良率的挑戰。','01','用工廠等料比喻運算單元等資料。接著指出：接得更近之後，製造難題轉移到接點與封裝。'),
 page('taxonomy','01 / 建立封裝地圖','結構、製程平台與商標是三個層次','同一個封裝，可以同時擁有結構分類與廠商平台名稱。',table('names',['層次','在描述什麼','例子'],[['結構','晶片如何相對排列與互連','MCM、2.5D、3D'],['製程平台','用什麼加工方式形成封裝','Fan-Out、晶圓級／面板級'],['廠商平台名稱','特定廠商的技術家族','CoWoS、SoIC、I-Cube、EMIB']]),'看到平台名稱後，仍要確認版本、結構與實際製程。','02','不要一次解釋所有縮寫。先讓大家分清三個問題：長什麼樣、怎麼做、誰的平台。'),
 page('cross-section','01 / 建立封裝地圖','CoWoS-S 的封裝剖面','剖面示意，不按比例；HBM 本身已經是一組垂直堆疊。',`<div class="gpm-section" data-key="section"><div class="gpm-dies"><div class="gpm-hbm" data-key="hbm-left" data-edit>HBM<br>記憶體堆疊</div><div class="gpm-logic" data-key="logic" data-edit>邏輯晶片</div><div class="gpm-hbm" data-key="hbm-right" data-edit>HBM<br>記憶體堆疊</div></div><div class="gpm-joints" data-key="bumps" data-edit>微凸塊：晶片與中介層之間的接點</div><div class="gpm-interposer" data-key="interposer" data-edit>矽中介層：水平細線 RDL ＋ 垂直通路 TSV</div><div class="gpm-joints" data-key="c4" data-edit>C4 接點</div><div class="gpm-substrate" data-key="substrate" data-edit>有機載板：把密集連線接向系統</div><div class="gpm-board" data-key="pcb" data-edit>BGA 錫球 ／ PCB 電路板</div></div>`,'從上到下看：晶片、中介層、載板與電路板各有不同角色。','02、03、06','先指並排的邏輯晶片與 HBM，再指 HBM 自己的堆疊。沿剖面向下走，強調中介層不等於載板。'),
 page('interconnect','01 / 建立封裝地圖','訊號要一路走過接點、細線與垂直通路','以 CoWoS-S 為例，這是一條簡化的對外連接路徑。',deck.steps('route',['晶片接墊','微凸塊','RDL 橫向走線','TSV 穿過矽','載板','PCB']),'RDL 解決平面內的重新配線；TSV 解決穿過矽的垂直連接。','03、06','回想上一頁剖面，在每一步說明訊號跨過哪個界面。提醒這是代表路徑，不是每種封裝都具備 TSV。'),
 page('workpiece','02 / 看懂實際製程','加工對象與支撐載具必須分開','同一條產線中，工件會改變形態，加工面也可能翻轉。',compare('piece','工件：最後成為產品的一部分','晶圓、裸晶、重組晶圓、面板、strip、封裝成品。不同形態需要不同搬運與加工能力。','載具：製程期間提供支撐','玻璃或矽 carrier 支撐薄工件，解黏後可檢查、清理並循環使用。'),'Carrier AOI 檢查的是載具表面；不能直接等同於產品晶圓檢測。','04','拿一張薄紙與托盤作口頭比喻。工件是紙，載具是托盤，托盤不良也可能傷到下一批工件。'),
 page('fanout','02 / 看懂實際製程','Fan-Out 把連線延伸到晶粒外側','重點是讓重新配線層跨出原晶粒面積。',compare('fanout','Chip-first：先放晶粒','排列晶粒 → 封膠形成重組體 → 製作 RDL。封膠後的 die shift 會增加對位難度。','Chip-last：先做配線','先建立 RDL → 再接上晶粒 → 封裝。重點轉向接合對位與配線良率。'),'製程順序改變，缺陷形成的位置與檢測時機也跟著改變。','05','用先放家具再拉線、先拉線再放家具作暫時比喻，隨即回到晶粒與 RDL。指出兩者都仍需控制對位。'),
 page('cowos-flow','02 / 看懂實際製程','CoW 組合晶片，WoS 接到載板','下列為教學合併流程，實際先後依廠商與世代調整。',deck.steps('cowos',['製作中介層','CoW：接晶片與 HBM','支撐、薄化與背面互連','切成模組','WoS：接到載板','補強與測試']),'「磨」出現在不同站點，但加工對象與品質指標各不相同。','06','對照剖面，把每一步指回所在位置。不要把流程上的每個研磨站都連到均豪，供應證據後面才談。'),
 page('variants','02 / 看懂實際製程','CoWoS-S、R、L 的互連材料不同','比較的是中介互連的做法，不是所有規格的高低排名。',table('variants',['版本','主要互連做法','要面對的取捨'],[['S','矽中介層與 TSV','細線能力與大面積矽製造負擔'],['R','RDL 中介互連','配線、尺寸與機械支撐'],['L','RDL 加局部矽互連 LSI','局部高密度與異質材料整合']]),'I-Cube 也需依版本判讀，不能把同一商標下的方案視為相同結構。','07','先問哪些區域真的需要最高密度，再解釋為何出現局部矽。不要把三個版本講成單一升級階梯。'),
 page('hbm','02 / 看懂實際製程','製造 HBM，與安裝 HBM，是不同工作','一組完成測試的 HBM 堆疊，才進入系統封裝整合。',compare('hbm','記憶體製造端','DRAM 晶粒薄化、TSV、堆疊接合與測試。MR-MUF、TC-NCF 等方法須按廠商與世代分開。','系統封裝端','將 HBM 與邏輯晶片對位接到中介互連結構，再完成載板、散熱與測試。'),'HBM 需求增加，仍不足以證明某設備商供應 HBM 薄化或堆疊設備。','08','先在腦中把 HBM 看成已做好的積木，再說明積木內部也有另一條製造流程。指出採購者與設備種類都可能不同。'),
 page('hybrid','02 / 看懂實際製程','混合鍵合要求兩種材料一起形成接合','示意：介電層貼合與銅接點連接共同構成界面，不按比例。',`<div class="gpm-bond" data-key="bond"><div class="gpm-bond-surface" data-key="top" data-edit>上層介電材料 <b>Cu</b> <b>Cu</b> <b>Cu</b></div><div class="gpm-interface" data-key="interface" data-edit>接合界面：顆粒、凹凸與偏移都可能造成空洞或開路</div><div class="gpm-bond-surface" data-key="bottom" data-edit>下層介電材料 <b>Cu</b> <b>Cu</b> <b>Cu</b></div><p data-key="requirements" data-edit>平坦化 → 清洗與活化 → 對位貼合 → 退火</p></div>`,'平坦、潔淨與對位要求一起提高；設備能力仍要用實際規格核對。','09','指銅接點與周圍介電材料，解釋混合指兩類材料。強調這是製程需求，不能直接推論均豪已供應此站。'),
 page('bridge','02 / 看懂實際製程','局部矽橋只服務需要密集互連的區域','共同想法是局部使用矽互連，但整合位置不同。',compare('bridge','EMIB','將局部矽橋嵌入載板，用來連接相鄰晶粒。版本如 EMIB-T 需另行判讀。','CoWoS-L','把 LSI 局部矽互連與 RDL 中介結構整合，再連到載板。'),'結構位置不同，製程站點與設備需求就不能整套互相套用。','10','用上一頁之前的載板與中介層位置，指出兩個橋放在哪裡。只比較架構，不宣稱性能誰全面勝出。'),
 page('inspection','03 / 從製程走向設備','缺陷藏在哪裡，決定怎麼檢查','沒有一種檢測方法能同時看見所有缺陷。',table('inspection',['問題','可用方法','主要邊界'],[['表面顆粒、刮傷','AOI','受光學對比與解析度限制'],['高度、共面性','白光干涉／3D 量測','幾何合格不保證電性導通'],['內部空洞','X-ray','穿透能力與解析度有取捨'],['界面剝離','超音波掃描 SAT','耦合介質與界面解析限制'],['是否導通','電性測試','可測接點與缺陷定位限制']]),'採購設備之前，先定義缺陷、尺寸、材料與檢測節拍。','11','逐列問：這個缺陷在表面還是裡面？用第二列說明外觀看起來平整仍可能不導通。'),
 page('grinding','03 / 從製程走向設備','「研磨」必須連同加工對象一起讀','厚度、厚度均勻性與表面粗糙度，回答的是不同問題。',table('grinding',['加工','目的','判讀重點'],[['元件晶圓背磨','減薄晶圓','厚度、TTV、破片'],['封膠／strip 研磨','調整封裝工件','材料、形態、平整度'],['CMP','化學機械平坦化','表面形貌與材料選擇性'],['再生晶圓磨拋','恢復再利用條件','回收晶圓用途與品質']]),'均豪公開磨拋產品的存在，不能證明其供應 HBM 薄化或 TSV 揭露。','12、15','先讀第一欄，強調加工對象。解釋 TTV 是同片不同位置的厚度差，與表面微觀粗糙程度不同。'),
 page('wet','03 / 從製程走向設備','濕製程的核心是「移除什麼、留下什麼」','化學液體接觸工件時，同時要顧到材料相容性。',table('wet',['操作','移除的對象','控制風險'],[['清洗','顆粒、污染與殘留','清不乾淨或傷及表面'],['蝕刻','指定材料','過蝕刻與選擇性不足'],['去膠','完成任務的光阻','殘膠與下層材料受損'],['顯影','曝光後應移除的光阻區域','圖形尺寸與殘留']]),'流程需要濕製程，不代表均豪已公開供應相應機種。','13','用模板做圖形的過程解釋顯影與去膠發生在不同時間。最後回到設備能力與供應證據要分開。'),
 page('yield','03 / 從製程走向設備','每站 99%，十站後只剩約 90.4%','教學假設：各站以進站工件為分母，沒有重工回收。',`<div class="gpm-yield" data-key="yield"><div data-key="y1"><span data-edit>單一站</span><div style="--fill:99%"><b>99.0%</b></div></div><div data-key="y10"><span data-edit>10 站連乘</span><div style="--fill:90.44%"><b>90.4%</b></div></div><div data-key="y20"><span data-edit>20 站連乘</span><div style="--fill:81.79%"><b>81.8%</b></div></div><p data-key="formula" data-edit>累積良率 = 各站條件良率相乘</p></div>`,'多加站點或降低某一站的良率，都會增加達到同樣良品需求所需的投入。','14，自建算例','先請聽眾猜十站後剩多少。再讀出連乘結果，說明為什麼缺陷應盡早被發現。'),
 {...page('capacity','03 / 從製程走向設備','需求增加，不一定需要新增設備','教學假設：每月 720 小時、現有 6 台。需求為本站良品目標，OEE 已含本站良品率，不另加重工係數。',`<div class="gpm-lab" data-key="lab"><div class="gpm-controls"><label>月需求（件）<input data-key="demand" type="range" min="50000" max="120000" step="10000" value="80000"><output data-key="demand-value">80,000</output></label><label>節拍（秒／件）<input data-key="seconds" type="range" min="60" max="180" step="10" value="120"><output data-key="seconds-value">120</output></label><label>設備綜合效率 OEE（%）<input data-key="oee" type="range" min="50" max="90" step="5" value="70"><output data-key="oee-value">70</output></label></div><div class="gpm-result" aria-live="polite"><div><small>單機有效月產能</small><strong data-key="monthly"></strong></div><div><small>所需台數</small><strong data-key="needed"></strong></div><div><small>已有 6 台，新增</small><strong data-key="added"></strong></div></div><p class="gpm-formula" data-key="formula" data-edit>OEE = 可用率 × 性能率 × 良品率，70% 以 0.70 代入<br>月產能 = (3,600 ÷ 節拍) × 720 × OEE<br>所需台數 = 需求 ÷ 單機月產能，無條件進位</p></div>`,'先算單站缺口，再問哪家設備商能供應；畫面數字不是均豪或客戶的實際數據。','14 的計算概念，改編為無額外重工模型','先把需求從五萬調到八萬：仍可由六台滿足。再調到十二萬，觀察新增台數；提高 OEE 或縮短節拍，看看缺口如何縮小。'),previewArt:capacityPreview,mount(root,state){
 const fields=['demand','seconds','oee'];
 const defaults={demand:80000,seconds:120,oee:70};
 const inputs=fields.map(k=>root.querySelector(`[data-key="${k}"]`));
 fields.forEach((k,i)=>{state[k]??=defaults[k];inputs[i].value=state[k];});
 const render=()=>{fields.forEach((k,i)=>{state[k]=Number(inputs[i].value);root.querySelector(`[data-key="${k}-value"]`).textContent=state[k].toLocaleString();});const r=capacity(state.demand,state.seconds,state.oee);['monthly','needed','added'].forEach(k=>root.querySelector(`[data-key="${k}"]`).textContent=(k==='monthly'?Math.round(r[k]):r[k]).toLocaleString());};
 inputs.forEach(el=>el.addEventListener('input',render));render();return()=>inputs.forEach(el=>el.removeEventListener('input',render));
 }},
 page('qualification','03 / 從製程走向設備','通過認證之後，還要等採購與驗收','設備導入可能失敗、延後，也可能再回到修改階段。',deck.steps('qualification',['送樣：確認能力','驗證：客戶端試跑','量產：正式採購','複製訂單：重複採購']),'這是書籍的分析框架，不是必然成功的時間表；認證不等於已認列營收。','14','先說流程箭頭只表示成功前進路徑，驗證也可能失敗。請聽眾在新聞中圈出認證、出貨與認列，分別定位。'),
 page('entities','04 / 回到均豪與公司消息','均豪、均華與聯盟成員要分開看','以下分工依本書快照整理，不將集團能力全部歸到均豪個體。',table('entities',['主體','書中主要分工','判讀方式'],[['均豪 5443','Wafer 級檢、量、磨、拋','主角的個體產品'],['均華 6640','Die 級 Sorter、Bonder','子公司，合併報表含其營收'],['志聖 2467','曝光、壓合等前段設備','聯盟及交叉持股，非均豪子公司'],['東捷','聯盟協作、承接溢出產能','聯盟關係不能當成同公司訂單']]),'先辨認是哪個公司拿到訂單，再談合併營收與股東獲利。','15，G1、G3、G6','讓大家記住均豪與均華只差一字，但產品分工不同。指出聯盟新聞未必代表均豪個體業務。'),
 page('products','04 / 回到均豪與公司消息','公開產品可對上需求，但供應範圍仍有限','轉述書中公司自述與媒體整理；狀態固定在 2026-08-31。',table('products',['均豪產品','加工／檢測對象','書中狀態'],[['Carrier AOI','循環載具表面','公司自述：已認證並量產'],['白光干涉','RDL 等幾何量測','公司自述：國內封裝測試代工廠（OSAT）認可、Q2 放量'],['再生晶圓 CMP／拋光','再生晶圓','公司自述：2025 放量'],['載板方形輪磨','PMIC 相關厚銅載板','公司自述：2026 H1 新成長線']]),'每列要保留自己的產品、工件、客戶稱呼與證據。','15，G1–G4','把每一列連回前面加工對象與量測方法。提醒認可、量產等文字是書籍轉述，不能延伸為今天的最新狀態。'),
 page('unknown','04 / 回到均豪與公司消息','驗證中的產品，與尚未證明的用途','產品進展與供應範圍是兩種不同的不確定性。',compare('unknown','書中列為開發或驗證階段','3D X-ray：公司自述認證中，目標 2027 貢獻營收。晶圓邊緣研磨：驗證中。8 吋 SiC CMP：媒體報導共同開發。','書中尚無足夠供應證據','不能確認 CoWoS 的 S／R／L 子平台、HBM 極薄化、元件晶圓背磨或 TSV 揭露站的具體供應。'),'缺少公開證據表示仍待查證，不能寫成已供應，也不能斷言不存在。','12、15，G1、G2、G5、G6','先區分有產品但還在驗證，與根本未能確認產品對應。2027 是原始目標，不是確定會實現的結果。'),
 page('evidence','04 / 回到均豪與公司消息','三則相似敘述，不能拼成同一筆供應','下表保留原本的未具名客戶，避免把不同來源的片段合併。',table('evidence',['產品','客戶稱呼','原書證據'],[['AOI','晶圓代工大廠先進封測廠區','媒體報導 G5'],['Carrier AOI','國際封裝大廠','公司自述 G2'],['白光干涉','國內 OSAT','公司自述 G2、G3']]),'本書快照內，沒有符合「雙方互相點名公告」等級的均豪客戶關係。','15、附錄 A','用手依序遮住不同列，確認單一列能支持什麼。問：哪份資料證明這三個客戶相同？書中沒有。'),
 page('scope','04 / 回到均豪與公司消息','合併表現，需要拆回公司與產品口徑','均華的營收會進合併報表，但它的 Bonder 不會因此變成均豪個體產品。',compare('scope','判讀營收結構','先問合併或個體，再問產品與期間。某業務占比提高，也可能伴隨其他業務減少。','判讀獲利品質','營收、營業利益、業外損益、歸屬母公司淨利各自回答不同問題。單月高峰不宜直接年化。'),'公司主體、報表口徑、期間與分母，四個條件要一起保留。','15、16','避免塞進新的財務數字。以子公司接到訂單為例，解釋合併營收、個體產品與歸母獲利不能互換。'),
 {...page('quiz','04 / 回到均豪與公司消息','練習：擴產消息能支持到哪裡？','假設消息：「某封裝廠產能將增加 60%，某設備商有相應檢測產品。」',`<div class="gpm-question" data-key="question-context" data-edit>這段消息尚未交代：<br><strong>瓶頸站點、既有設備餘裕、供應關係。</strong></div>`,'先選一個判斷，再說明還缺哪項證據。','16，教學情境','請聽眾先選，不急著公布。回答後再請他補上：如果要推估訂單，至少需要哪一個工廠與哪一站的資料。'),question:{prompt:'可以直接得出哪個結論？',choices:[{value:'orders',label:'設備商訂單會增加 60%',feedback:'缺少站點缺口與供應份額，無法把擴產倍率直接當成訂單倍率。'},{value:'check',label:'有需求方向，但要繼續查站點與供應',feedback:'對。還要確認瓶頸、既有餘裕、設備導入階段與供應關係。'},{value:'none',label:'設備商完全不可能受惠',feedback:'證據不足不代表不可能。應保留假設並列出可驗證條件。'}]}},
 page('template','04 / 回到均豪與公司消息','一份可以反覆使用的消息分析紀錄','每次讀新聞，都留下同一組可被後續資料檢查的欄位。',deck.steps('template',['誰／何時／原話','產品與製程站點','客戶與證據等級','驗證或量產階段','事實／推論／未知','何種觀察會翻案']),'把「我相信什麼」寫成「哪個證據出現時，我會修改判斷」。','16','拿前一頁情境口頭填一遍。強調找不到供應證據也可以完成紀錄，只要把它留在未知欄。'),
 page('reading','05 / 回到原書','依你要解決的問題回到章節','本簡報濃縮全書，原書保留更完整的流程、理解題與待查事項。',table('reading',['目的','建議章節','主要收穫'],[['讀懂公司消息','01、02、04、11、14–16','結構、設備與證據的連接'],['理解製程','03、05–10、12、13','工件、互連與加工條件'],['查來源與疑問','附錄 A、B、C','來源範圍、術語與待查事項']]),'公司資料截至 2026-08-31；原書技術來源多為既有整理，未逐份重核原文。','00-map、附錄 A','指出頁首附件有離線來源索引。提醒聽眾：若要做最新判斷，需另外查核新公告，本導讀沒有進行更新。'),
 deck.end({title:'先看工件與站點<br>再看供應證據',instruction:'收尾請大家用一句話說出：設備能力與供應關係之間還缺什麼。可以回到證據矩陣或產能算例重看。'}),
 ]
};


// 原書 Commons 圖片：遠端載入，保留作者、授權與檔案頁。
const wikiImages = [
 {id:'ai',file:'AMD_Fiji_GPU_package_with_GPU,_HBM_memory_and_interposer.jpg',alt:'AMD Fiji 封裝：中央 GPU 與周圍 HBM 共置於中介層上',caption:'實物例：GPU 與 HBM 共同封裝；不是均豪產品或供應證據。',author:'C. Spille／pcgameshardware.de',license:'CC BY-SA 4.0',url:'https://creativecommons.org/licenses/by-sa/4.0/'},
 {id:'workpiece',file:'ICC_2008_Poland_Silicon_Wafer_1_edit.png',alt:'已完成電路的矽晶圓，每個小格對應晶粒區域',caption:'工件實物：已完成電路的晶圓；支撐載具是另外的物件。',author:'FxJ',license:'公有領域',url:'https://commons.wikimedia.org/wiki/File:ICC_2008_Poland_Silicon_Wafer_1_edit.png'},
 {id:'hbm',file:'High_Bandwidth_Memory_schematic.svg',alt:'HBM 剖面示意：記憶體堆疊與邏輯晶片透過中介層連接',caption:'HBM 剖面示意；非特定世代規格，不按比例。',author:'ScotXW／Shmuel Csaba Otto Traian',license:'CC BY-SA 4.0',url:'https://creativecommons.org/licenses/by-sa/4.0/'}
];
for(const picture of wikiImages){
 const slide=story.pages.find(p=>p.id===picture.id);
 const commons='https://commons.wikimedia.org/wiki/File:'+encodeURIComponent(picture.file);
 const image='https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(picture.file)+'?width=900';
 slide.art='<div class="gpm-illustrated" data-key="illustrated"><figure class="gpm-wiki" data-key="wiki-image"><a href="'+commons+'" target="_blank" rel="noopener noreferrer"><img src="'+image+'" alt="'+picture.alt+'" loading="lazy" referrerpolicy="no-referrer"></a><figcaption><span data-key="wiki-caption" data-edit>'+picture.caption+'</span><small>'+picture.author+' · <a href="'+picture.url+'" target="_blank" rel="noopener noreferrer">'+picture.license+'</a> · <a href="'+commons+'" target="_blank" rel="noopener noreferrer">Commons 原圖</a> · 未修改</small></figcaption></figure><div class="gpm-image-context">'+slide.art+'</div></div>';
 slide.detail+=' 圖片沿用原書附錄 D，需連網載入。';
}
