[book]
title = "GPU 完整學習指南"
authors = ["Edison Hsieh"]
language = "zh-Hant"
src = "src"

[build]
build-dir = "html"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = ""
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]
fold.enable = true
fold.level = 1
