-- 管理員：僅在獨立 SQL Server 2022 開發實例執行；以 sqlcmd -b 停止錯誤。
-- 保護、建庫、設定處於同一個外層批次，拒絕後不會繼續 ALTER 既有库。
USE master;
IF DB_ID(N'B02Lab') IS NOT NULL
    THROW 51000, N'B02Lab 已存在；拒絕覆蓋。請保留證據並人工決定下一步。', 1;
BEGIN TRY
    EXEC(N'CREATE DATABASE B02Lab;');
    ALTER DATABASE B02Lab SET COMPATIBILITY_LEVEL = 160;
    ALTER DATABASE B02Lab SET READ_COMMITTED_SNAPSHOT OFF;
    ALTER DATABASE B02Lab SET ALLOW_SNAPSHOT_ISOLATION OFF;
    ALTER DATABASE B02Lab SET DELAYED_DURABILITY = DISABLED;
END TRY
BEGIN CATCH
    THROW;
END CATCH;
GO
